# [ Database Configuration Section ]
spring:
  profiles:
    active: dev

# [ AppServer Configuration Section ]
server: 
  port: ${management.service.port:8680}
  context-path: /lcmarket
  
---
spring:
  profiles: dev
  # [Database configuration]
  jpa: 
    properties:
       hibernate:
          hbm2ddl.auto: ${hbm2ddl.auto:update}
          dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  datasource:
    platform: sql-server
    url: jdbc:postgresql://${sql-server.hostname:localhost}:${sql-server.port:5432}/${sql-server.dbname:lcmarketdb}
    driver-class-name: org.postgresql.Driver
    username: ${sql-server.username:postgres}
    password: ${sql-server.password:postgres}